### ISSUE TITLE
unable to clone repo

### ISSUE THREAD

**Issue by mithilaunkule** [Bioforest-project/inventories#13]
I am not able to clone this repo on my local rstudio, and I'm not sure why. It keeps loading and compressing objects, never finishing. Are there any heavy files that are too heavy for my weak computer to handle? Or am I doing something wrong? I managed to clone the other repos

**Comment by mithilaunkule** [comment]
> I am not able to clone this repo on my local rstudio, and I'm not sure why. It keeps loading and compressing objects, never finishing. Are there any heavy files that are too heavy for my weak computer to handle? Or am I doing something wrong? I managed to clone the other repos

And now i get this error, but unable to find a solution
![git_clone_error](https://github.com/user-attachments/assets/a2598c6c-fa58-4826-9eb2-10fadebab59c)

**Comment by sylvainschmitt** [comment]
This is working perfectly fine on my side when I try a new clone. Try deleting the repo and re-cloning it with either Rstudio, Git-gui, or GitHub Desktop. And if you still don't manage you can always download the archive, unzip it where you want the project to be and open it with Rstudio. I'm closing the issue because this is to my mind a local computer issue but do not hesitate to reopen it if you still have difficulties.
